### ISSUE TITLE
Code on login page doesn't always run, sometimes requires refresh

### ISSUE THREAD

**Issue by rylandbell** [hendricksonsarahl/voluntr#139]

**Comment by hendricksonsarahl** [comment]
I haven't been able to reproduce this bug, is this still an issue? Or could it be browser/machine specific?

**Comment by rylandbell** [comment]
I haven't either, but I haven't intentionally done anything to fix it. It might have been a caching issue while I was actively working on related code. I'd still like to hammer on it one more time to see if I can reproduce it, but it might not actually be a bug.

**Comment by rylandbell** [comment]
I would get the Google button to say "Signed in with Google", but then neither of my JS outcomes would trigger. It wouldn't show the sign-up form, or redirect to the signed-in view.
