### ISSUE TITLE
make it possible to filter by multiple categories

### ISSUE THREAD

**Issue by AdamD-2096** [hendricksonsarahl/voluntr#144]
after this is done we will need the "Any Category" button to uncheck all others if checked, and uncheck itself if anything else is checked
do you know how to do that @rylandbell

**Comment by rylandbell** [comment]
Don't worry about the "Any Category" case. I'll figure something out in the browser with JavaScript. @AdamD-2096

**Comment by AdamD-2096** [comment]
could you explain what you're talking about?
do you mean js that will change the checkboxes if certain things are checked.
or something else?

**Comment by rylandbell** [comment]
I'm envisioning a button to select/un-select all of the checkboxes. The JavaScript will do the "clicking" on the checkboxes, but the output to the server won't be any different (we just won't ever explicitly send "all" to the server.)

**Comment by rylandbell** [comment]
I'll also use JS to prevent submission of a form with zero checked categories.
