### ISSUE TITLE
Typo in "flexible schedule", opp view

### ISSUE THREAD

**Issue by hendricksonsarahl** [hendricksonsarahl/voluntr#150]
There's a comma following "Flexible schedule" only in one place under "When", but it shows for every opp marked as Flexible schedule. May be related to CSV data. 
<img width="380" alt="flexible schedule bug" src="https://user-images.githubusercontent.com/28641430/32066208-e6807fb0-ba33-11e7-86a5-3d4805e561c7.png">
See attached image

**Comment by rylandbell** [comment]
Haha, I have a PR ready to go for this. Just waiting for the other open PRs to merge first. Thanks for documenting it!

**Comment by razzlepdx** [comment]
another 1 character PR!
