### ISSUE TITLE
add option for `Flexible Schedule` to the `/org/add` form

### ISSUE THREAD

**Issue by razzlepdx** [hendricksonsarahl/voluntr#152]
When organizations are filling out the form to add a new opportunity, they currently need to pick a specific time and date.  Since this is not always true for opportunities, it would be nice to give the organization an option to state that the timing of this opportunity is flexible.  

A possible solution is adding a pair of radio buttons to the form:
- the first radio button would contain the flexible schedule option
- the second radio button would hold the date and time input fields.   
- update voluntr.py and possibly the helper functions to account for the new data coming in.  

This is a low priority issue, and might not be completed by Nov. 2, but I'd like to implement it before the next major release.

**Comment by rylandbell** [comment]
@razzlepdx Mind if I take over this issue?
