### ISSUE TITLE
"Post a New Opportunity" form displays but submission fails

### ISSUE THREAD

**Issue by hendricksonsarahl** [hendricksonsarahl/voluntr#167]
Nonprofit registration via Google OAuth now functions, but **"easily submit open volunteer opportunities"** is failing and will need to be modified to work for dynamic accounts rather than the static test account. Upon submission: "Bad Request" error

**Comment by rylandbell** [comment]
I added a bug fix for the "Bad Request" error. We'll still need to convert away from the hard-coded org ID, but I don't think we need a separate issue for this page, since we'll be doing that for many of the org routes.

**Comment by hendricksonsarahl** [comment]
Makes sense, thanks Ryland!
