### ISSUE TITLE
Delete Opp buttons on org side should trigger server to mark opps as removed

### ISSUE THREAD

**Issue by rylandbell** [hendricksonsarahl/voluntr#169]
- I think we should not allow orgs to delete opps from the DB, but rather mark them as "removed" (or whatever). This seems like a good practice in general; in particular, it will help us give volunteers good feedback if they try to access an opp they had saved that has since been deleted.
- As a separate issue (#163), we should write a browser feature to hide delete buttons behind a confirmation process.

**Comment by AdamD-2096** [comment]
would we then also have a view or some kind of something for orgs to view all of there removed opps
side note i think an easy way to achieved removed is with another column in the DB on opps that is a Boolean. like True for current and False for removed
(i don't know how far along you are, but i figured better so say something not needed that not say something that could be helpful)
