### ISSUE TITLE
[SUGGESTION] Research storage options for mySQL data

### ISSUE THREAD

**Issue by razzlepdx** [hendricksonsarahl/voluntr#20]
We need to determine where our volunteer/organizational data can be stored after deployment.  I haven't found many free, stable options, but have only taken a very cursory look around.  If someone else is interested in researching this point, feel free to assign yourself!  Otherwise, I recommend that we use MAMP in the development/testing stages and look into a more permanent solution during our final sprint.

**Comment by hendricksonsarahl** [comment]
I looked into this some more this morning and I agree that it seems for now, MAMP - phpMyAdmin is the best solution as we build and test this. I have these steps included in the setup.md file for now, we can always change this later if a better solution is available

**Comment by hendricksonsarahl** [comment]
For now, we have decided on the use of MAMP locally. When deploying as a product we will have to have a paid version
