### ISSUE TITLE
document the process of creating a mamp database and setting it up

### ISSUE THREAD

**Issue by razzlepdx** [hendricksonsarahl/voluntr#21]

**Comment by AdamD-2096** [comment]
mamp database user name and password = voluntr

**Comment by AdamD-2096** [comment]
so about the documentation!
where should it be put?
what kind of file would be preferred?
and what all would you like in it?

**Comment by hendricksonsarahl** [comment]
@AdamD-2096 I'll set up a couple of files to store the documentation in to give us a place to start!

**Comment by hendricksonsarahl** [comment]
PR #31 resolved this issue, closing
