### ISSUE TITLE
Deploy Heroku in new group account

### ISSUE THREAD

**Issue by hendricksonsarahl** [hendricksonsarahl/voluntr#212]
Create new Heroku account that we all have access to managing / database access

**Comment by rylandbell** [comment]
I did a little research, and I don't think that a Heroku team account makes sense for us right now (no free tier). Instead, everybody who would like access to the Voluntr Heroku deployment should create a personal Heroku account and send me the email used for that account. I can add you as a collaborator, and you should have full admin access.

I recommend practicing first with something other than the production Voluntr app. Heroku apps are easy to delete, and hard to accidentally find, so you can deploy whatever there (like an old app you worked on?) Here's a good tutorial: https://devcenter.heroku.com/articles/getting-started-with-python#introduction.

(We're also using the add-on MySQL service ClearDB, which might also be worth practicing with.)

**Comment by rylandbell** [comment]
I don't think this is a super-high priority, but it would be nice to have at least one more person set up here.

**Comment by hendricksonsarahl** [comment]
@rylandbell Nice! I didn't know about the collaborator option, I think that'd be great! Now that I know that we're sticking with this site url for now I can tackle a couple more issues. Feel free to add me as a collaborator:
**hendricksonsarahl@gmail.com**

**Comment by rylandbell** [comment]
I'm considering this resolved, and closing it.
