### ISSUE TITLE
What's the best practice for handling drop/create-type actions in a deployed environment?

### ISSUE THREAD

**Issue by rylandbell** [hendricksonsarahl/voluntr#223]

**Comment by hendricksonsarahl** [comment]
Researching this now - if anyone else already has ideas feel free to comment here / assign yourself!

**Comment by hendricksonsarahl** [comment]
From what I'm gathering and the more I think about it, I think we should treat our deployed database as the real thing including data we don't want to quickly drop from our tables. In cases where we have test data we need to remove, or new migrations we need to make to reflect on the deployed side, we should be able to do those things in phpMyAdmin. The sql commands are good to stay sharp on, and if you don't know them or don't want to get into those phpMyAdmin has nice buttons for those actions without any code. We'll all need to get on a shared Heroku account (issue #212) and I believe there's a way we can still have a drop_create route for local testing which is not on our deployed server. 

If anyone else has other thoughts or ideas on this, feel free to share them! I'll leave this issue open for now in case anyone wants to comment.

**Comment by rylandbell** [comment]
That all sounds good to me. I'll add a comment on issue #219 to disable `/drop_create` on the deployed app.
