### ISSUE TITLE
Organize sprint notes in repo

### ISSUE THREAD

**Issue by hendricksonsarahl** [hendricksonsarahl/voluntr#242]
- The "projects" section I tried to adapt for notes storage has hit a wall. There's a character limit per "card", and there's a lot of other features we don't need for note purposes. 
- I've seen other group projects store meeting notes in a markdown file within the repo. Going to try this method and see what the team thinks!

**Comment by hendricksonsarahl** [comment]
I think the best method would be to have an issue for the active Sprint, with documented sections for "Goals", "Notes" and "Discussion", designed so we can each update status / notes as we want throughout the sprint, at meetings, and close in the end-of-sprint meeting. Will set that up for this Clean-Up sprint and we'll see if we want to stick with it!

**Comment by hendricksonsarahl** [comment]
Notes from the last two standups have been formed into an ongoing "Sprint" issue. This issue would stay open for reference and discussion as we work through the sprint and as a checklist in our end-of-sprint standups. Check it out [here](https://github.com/hendricksonsarahl/voluntr/issues/243) and let me know if you have any questions or suggestions!

**Comment by hendricksonsarahl** [comment]
@rylandbell @AdamD-2096 @razzlepdx Since this issue will be closed without a PR, I'll request that you review this issue by reading through these comments :)

**Comment by razzlepdx** [comment]
sounds like a great plan to me!

**Comment by hendricksonsarahl** [comment]
Upon setting up #243 this issue is closed 🌮

**Comment by hendricksonsarahl** [comment]
Upon setting up #243 this issue is closed 🌮
