### ISSUE TITLE
Research and implement OAuth

### ISSUE THREAD

**Issue by hendricksonsarahl** [hendricksonsarahl/voluntr#36]
Research a Flask compatible OAuth library for Org login via Google OAuth. See if the time requirements work for MVP, if not start account management internally

[OAuth Authentication with Flask](https://blog.miguelgrinberg.com/post/oauth-authentication-with-flask)

**Comment by rylandbell** [comment]
That is a very ominous-sounding title.

**Comment by hendricksonsarahl** [comment]
PR #45 and #47 resolves this issue. 

Primary resources for integration: 
- [Google Sign-In for Web](https://developers.google.com/identity/sign-in/web/)
- [Google Cloud Console - API Credentials](https://console.cloud.google.com/apis/credentials?project=voluntr-182617) _requires login_
