### ISSUE TITLE
Create test plan and update README.md user story section

### ISSUE THREAD

**Issue by hendricksonsarahl** [hendricksonsarahl/voluntr#56]
From [Launch Code Unit 4 documentation](http://education.launchcode.org/lc101-unit4-portland/assignments/): 
"Tests
A test plan is required. This can be a simple markdown document or section of your README that says, "We'll use manual testing to verify our scenarios" with a table of results.

Automated unit tests of models are a stretch goal. We'll be covering this in class, so you can apply what you learn in your project.

Automated end-to-end tests of controllers are a stretch goal, but we won't be covering this in class."

Add test status in a column to existing user story tables

**Comment by razzlepdx** [comment]
This issue is resolved by PR #60
