### ISSUE TITLE
find suitable background image for each category

### ISSUE THREAD

**Issue by rylandbell** [hendricksonsarahl/voluntr#68]
This site has some nice free-use images: https://unsplash.com/.

**Comment by rylandbell** [comment]
@hendricksonsarahl , we thought you'd enjoy this one.

**Comment by rylandbell** [comment]
We decided to include a single image for each category (see the CSV file), and then name them [categoryName].jpg and use jinja to display an appropriate header image. The images should end up in the `static/images/` folder.

**Comment by rylandbell** [comment]
These are the category names we'll need images for:

animals
arts_culture
community
disabilties
education_lit
health_med
houseless
hunger
kids_youth

I named the Oregon Food Bank image `hunger.jpg`, but feel free to replace it with a different image.

@hendricksonsarahl

**Comment by hendricksonsarahl** [comment]
Looks great! I'll get started on this today

**Comment by hendricksonsarahl** [comment]
Issue resolved via PR #82
