### ISSUE TITLE
Org sign-in should redirect to org/opportunities

### ISSUE THREAD

**Issue by hendricksonsarahl** [hendricksonsarahl/voluntr#98]
- Currently, once an org is signed up or signed in, the current page reloads 
- The home nav goes back to the original landing page, not the Org homepage of org/opportunities
- Need to pass the Org ID back to the server to populate the correct org homepage upon sign-in

**Comment by rylandbell** [comment]
I've taken care of the redirecting with my work for issue #83 . It doesn't actually redirect yet because we aren't actually creating user accounts yet. Once those are set up, we'll get the Org ID from the OAuth token that we send via cookies. (@sarah)
